<a href="https://colab.research.google.com/github/pranavlandge36/ml-learning-notebooks/blob/main/Pytorch-Learning/%20Pytorch_Traning_Pipeline_using_Dataset%26DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Creating a Dataset form scratch

import torch
from sklearn.datasets import make_classification



In [ ]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_classes=2,
    random_state=42,
    n_informative=2,
    n_redundant=0
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
type(X)

numpy.ndarray

In [ ]:
# converting to tensors
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [ ]:
from torch.utils.data import DataLoader,Dataset


In [ ]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.labels= labels
    self.features= features
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


In [ ]:
dataset=CustomDataset(X,y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [ ]:
dataloader=DataLoader(batch_size=2,shuffle=True,dataset=dataset)

In [ ]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print('-'*50)
  print(batch_labels)

tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]])
--------------------------------------------------
tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]])
--------------------------------------------------
tensor([1, 1])
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
--------------------------------------------------
tensor([1, 1])
tensor([[-0.5872, -1.9717],
        [-1.1402, -0.8388]])
--------------------------------------------------
tensor([0, 0])
tensor([[-1.9629, -0.9923],
        [-2.8954,  1.9769]])
--------------------------------------------------
tensor([0, 0])


Using Dataset

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [ ]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [ ]:
scali=StandardScaler()
X_train=scali.fit_transform(X_train)
X_test=scali.transform(X_test)

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
x_train_tensor=torch.tensor(X_train,dtype=torch.float64)
y_train_tensor=torch.tensor(y_train,dtype=torch.float64)
x_test_tensor=torch.tensor(X_test,dtype=torch.float64)
y_test_tensor=torch.tensor(y_test,dtype=torch.float64)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.labels= labels
    self.features= features
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


In [ ]:
train_dataset=CustomDataset(x_train_tensor,y_train_tensor)
test_dataset=CustomDataset(x_test_tensor,y_test_tensor)

In [ ]:
train_loader=DataLoader(dataset=train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(dataset=test_dataset,batch_size=32,shuffle=True)

In [ ]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# create model
model = MySimpleNN(x_test_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [ ]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features.float()) # Convert input features to float32

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1).float()) # Convert labels to float32 for BCELoss

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.11767435073852539
Epoch: 2, Loss: 0.09497933089733124
Epoch: 3, Loss: 0.17782878875732422
Epoch: 4, Loss: 0.122466541826725
Epoch: 5, Loss: 0.11984584480524063
Epoch: 6, Loss: 0.09799329191446304
Epoch: 7, Loss: 0.203914612531662
Epoch: 8, Loss: 0.1200886219739914
Epoch: 9, Loss: 0.22334888577461243
Epoch: 10, Loss: 0.1566629409790039
Epoch: 11, Loss: 0.1435607373714447
Epoch: 12, Loss: 0.025669360533356667
Epoch: 13, Loss: 0.04960514232516289
Epoch: 14, Loss: 0.020834261551499367
Epoch: 15, Loss: 0.08127451688051224
Epoch: 16, Loss: 0.07606057077646255
Epoch: 17, Loss: 0.0971800908446312
Epoch: 18, Loss: 0.0028137315530329943
Epoch: 19, Loss: 0.021964874118566513
Epoch: 20, Loss: 0.086064413189888
Epoch: 21, Loss: 0.018580611795186996
Epoch: 22, Loss: 0.08336818963289261
Epoch: 23, Loss: 0.006038215011358261
Epoch: 24, Loss: 0.04230695962905884
Epoch: 25, Loss: 0.019829796627163887


In [ ]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features.float())
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9470
