<a href="https://colab.research.google.com/github/pranavlandge36/ml-learning-notebooks/blob/main/Pytorch-Learning/Pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

Simple implementation of nn module.

In [4]:
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__() ## IMPORTANT USED TO CALL/USE NN MODLUE FUNCTIONS
    self.linear= nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self,features):
      out=self.linear(features)
      out=self.sigmoid(out)

      return out

In [5]:
## Creating dataset
features=torch.rand(10,5)

# creating model
model=Model(features.shape[1])

# making predictions/ calling model for forward pass
model(features)

tensor([[0.4227],
        [0.4327],
        [0.4664],
        [0.4050],
        [0.3733],
        [0.5243],
        [0.4790],
        [0.5327],
        [0.4438],
        [0.4674]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[-0.4292,  0.1532, -0.3356, -0.1198,  0.3721]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([0.0369], requires_grad=True)

In [8]:
!pip install torchinfo
from torchinfo import summary
summary(model,input_size=[10,5])

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Now creating one with 5 input , 3 hidden neurons, one output

In [3]:
!pip install torchinfo
from torchinfo import summary


class Model2(nn.Module):
  def __init__(self,num_features):
     super().__init__()
     self.linear1=nn.Linear(num_features,3)
     self.relu=nn.ReLU()
     self.linear2=nn.Linear(3,1)
     self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out

# creating dataset
features=torch.rand(100,5)
model=Model2(features.shape[1])
model(features)

tensor([[0.6203],
        [0.6041],
        [0.5968],
        [0.6021],
        [0.5148],
        [0.6347],
        [0.6480],
        [0.5421],
        [0.5524],
        [0.5935],
        [0.6341],
        [0.6393],
        [0.5768],
        [0.6462],
        [0.5832],
        [0.5426],
        [0.6154],
        [0.6118],
        [0.5891],
        [0.5938],
        [0.5959],
        [0.5729],
        [0.5540],
        [0.6086],
        [0.6320],
        [0.6233],
        [0.5906],
        [0.5685],
        [0.6448],
        [0.6146],
        [0.5756],
        [0.5905],
        [0.5705],
        [0.5953],
        [0.5867],
        [0.5386],
        [0.5628],
        [0.6084],
        [0.6229],
        [0.5780],
        [0.5343],
        [0.5330],
        [0.5609],
        [0.5623],
        [0.5676],
        [0.6021],
        [0.5909],
        [0.5765],
        [0.5855],
        [0.5733],
        [0.5656],
        [0.5452],
        [0.6099],
        [0.5998],
        [0.6195],
        [0

In [4]:
print(model.linear1.weight)

print(model.linear1.bias)

print(model.linear2.weight)

print(model.linear2.bias)


Parameter containing:
tensor([[-0.0418, -0.4207,  0.4424,  0.2924,  0.3057],
        [ 0.1752,  0.4074,  0.4091, -0.2408,  0.1000],
        [ 0.1149,  0.2973,  0.1520, -0.0839, -0.1456]], requires_grad=True)
Parameter containing:
tensor([0.0346, 0.3993, 0.3921], requires_grad=True)
Parameter containing:
tensor([[0.1029, 0.5510, 0.1383]], requires_grad=True)
Parameter containing:
tensor([-0.2207], requires_grad=True)


In [5]:
summary(model,input_size=(100,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [100, 1]                  --
├─Linear: 1-1                            [100, 3]                  18
├─ReLU: 1-2                              [100, 3]                  --
├─Linear: 1-3                            [100, 1]                  4
├─Sigmoid: 1-4                           [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

Using Sequential Container

In [9]:
class Model3(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,features):
    out=self.network(features)
    return out

features=torch.rand(100,5)
model=Model3(features.shape[1])
model(features)

tensor([[0.3634],
        [0.3620],
        [0.3439],
        [0.3596],
        [0.3621],
        [0.3662],
        [0.3475],
        [0.3617],
        [0.3567],
        [0.3554],
        [0.3414],
        [0.3556],
        [0.3607],
        [0.3544],
        [0.3520],
        [0.3638],
        [0.3672],
        [0.3499],
        [0.3441],
        [0.3561],
        [0.3515],
        [0.3637],
        [0.3384],
        [0.3546],
        [0.3584],
        [0.3523],
        [0.3544],
        [0.3596],
        [0.3502],
        [0.3604],
        [0.3591],
        [0.3391],
        [0.3571],
        [0.3462],
        [0.3721],
        [0.3466],
        [0.3468],
        [0.3569],
        [0.3482],
        [0.3594],
        [0.3480],
        [0.3606],
        [0.3764],
        [0.3532],
        [0.3402],
        [0.3559],
        [0.3631],
        [0.3453],
        [0.3314],
        [0.3626],
        [0.3621],
        [0.3402],
        [0.3519],
        [0.3696],
        [0.3509],
        [0

Using dataset

In [11]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [13]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [14]:
df.shape

(569, 31)

In [15]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [16]:
scali=StandardScaler()
X_train=scali.fit_transform(X_train)
X_test=scali.transform(X_test)

In [17]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [28]:
x_train_tensor=torch.tensor(X_train,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
x_test_tensor=torch.tensor(X_test,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

In [29]:
x_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

In [31]:
class SimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

  #  # binary loss function
  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
  #   return loss

In [37]:
learning_rate=0.1
epochs=200

loss_function=nn.BCELoss()


model=SimpleNN(x_train_tensor.shape[1])

optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):
  y_pred=model.forward(x_train_tensor)

  loss=loss_function(y_pred,y_train_tensor.view(-1,1))

  loss.backward()

  # with torch.no_grad():
  #   model.linear.weight.sub_(learning_rate * model.linear.weight.grad)
  #   model.linear.bias.sub_(learning_rate * model.linear.bias.grad)

  optimizer.step()


  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()
  print(f'epoch: {epoch+1},loss:{loss.item()}')

epoch: 1,loss:0.6146737337112427
epoch: 2,loss:0.4915168881416321
epoch: 3,loss:0.4212137758731842
epoch: 4,loss:0.37490978837013245
epoch: 5,loss:0.341534286737442
epoch: 6,loss:0.31601426005363464
epoch: 7,loss:0.2956782281398773
epoch: 8,loss:0.27897319197654724
epoch: 9,loss:0.2649283707141876
epoch: 10,loss:0.25290194153785706
epoch: 11,loss:0.24245086312294006
epoch: 12,loss:0.23325808346271515
epoch: 13,loss:0.22508981823921204
epoch: 14,loss:0.217769593000412
epoch: 15,loss:0.2111613005399704
epoch: 16,loss:0.20515795052051544
epoch: 17,loss:0.19967426359653473
epoch: 18,loss:0.19464111328125
epoch: 19,loss:0.19000189006328583
epoch: 20,loss:0.1857096403837204
epoch: 21,loss:0.18172506988048553
epoch: 22,loss:0.17801491916179657
epoch: 23,loss:0.17455081641674042
epoch: 24,loss:0.17130844295024872
epoch: 25,loss:0.1682666391134262
epoch: 26,loss:0.1654069870710373
epoch: 27,loss:0.16271334886550903
epoch: 28,loss:0.1601715087890625
epoch: 29,loss:0.1577688306570053
epoch: 30,lo

In [38]:
model.linear.weight

Parameter containing:
tensor([[ 0.4378,  0.3897,  0.5405,  0.3509,  0.1642,  0.2462,  0.3775,  0.5529,
          0.0431, -0.2054,  0.4376, -0.0727,  0.4889,  0.2722,  0.0723, -0.1809,
         -0.0475,  0.1478, -0.1329, -0.3159,  0.5914,  0.5421,  0.3693,  0.6573,
          0.3497,  0.1957,  0.2264,  0.5391,  0.3457,  0.1719]],
       requires_grad=True)

In [39]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5507848858833313
